ALTER TABLE teams
ADD COLUMN IF NOT EXISTS reached_round_of_32 BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS reached_round_of_16 BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS reached_quarter_final BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS reached_semi_final BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS reached_final BOOLEAN DEFAULT FALSE;
