export const TEAM_FLAGS = {
  Alemania: '🇩🇪',
  'Arabia Saudí': '🇸🇦',
  Argelia: '🇩🇿',
  Argentina: '🇦🇷',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Bélgica: '🇧🇪',
  'Bosnia y Herzegovina': '🇧🇦',
  Brasil: '🇧🇷',
  'Cabo Verde': '🇨🇻',
  Canadá: '🇨🇦',
  Catar: '🇶🇦',
  Colombia: '🇨🇴',
  'Corea del Sur': '🇰🇷',
  'Costa de Marfil': '🇨🇮',
  Croacia: '🇭🇷',
  Curazao: '🇨🇼',
  Ecuador: '🇪🇨',
  Egipto: '🇪🇬',
  Escocia: '🏴',
  España: '🇪🇸',
  'Estados Unidos': '🇺🇸',
  Francia: '🇫🇷',
  Ghana: '🇬🇭',
  Haití: '🇭🇹',
  Inglaterra: '🏴',
  Irak: '🇮🇶',
  Irán: '🇮🇷',
  Japón: '🇯🇵',
  Jordania: '🇯🇴',
  Marruecos: '🇲🇦',
  México: '🇲🇽',
  Noruega: '🇳🇴',
  'Nueva Zelanda': '🇳🇿',
  'Países Bajos': '🇳🇱',
  Panamá: '🇵🇦',
  Paraguay: '🇵🇾',
  Portugal: '🇵🇹',
  'RD Congo': '🇨🇩',
  'República Checa': '🇨🇿',
  Senegal: '🇸🇳',
  Sudáfrica: '🇿🇦',
  Suecia: '🇸🇪',
  Suiza: '🇨🇭',
  Túnez: '🇹🇳',
  Turquía: '🇹🇷',
  Uruguay: '🇺🇾',
  Uzbekistán: '🇺🇿'
}

export function getTeamFlag(name) {
  return TEAM_FLAGS[name] || '🏳️'
}
